### ISSUE TITLE
Error on example code

### ISSUE THREAD

**Issue by Berkmann18** [tgetgood/whodunnit#11]
When I run
```bash
name-your-contributors -u mntnr -r name-your-contributors -t $GITHUB_TOKEN > nyc.json
cat nyc.json | whodidwhat
```
I get this (same output as `name-your-... | whodidwhat`):
```bash
TypeError: Cannot read property 'map' of undefined
  at cat (/usr/lib/node_modules/whodidwhat/src/index.js:20:20)
  at loopField (/usr/lib/node_modules/whodidwhat/src/index.js:23:30)
  at typeMap.map (/usr/lib/node_modules/whodidwhat/src/index.js:46:27)
  at Array.map (<anonymous>)
  at byUser (/usr/lib/node_modules/whodidwhat/src/index.js:46:11)
  at process._tickCallback (internal/process/next_tick.js:68:7)
```

I had a quick look at the code but couldn't really understand why that was happening.

To reproduce this, do the following:
```bash
npm i -g name-your-contributors whodidwhat
export GITHUB_TOKEN=yourTokenHere
name-your-contributors -u mntnr -r name-your-contributors -t $GITHUB_TOKEN > nyc.json
cat nyc.json | whodidwhat
```

EDIT: This doesn't happen when using `cli.js` on a repo clone.

**Comment by RichardLitt** [comment]
I had the same issue.

**Comment by Berkmann18** [comment]
Do you know what could cause that?

**Comment by RichardLitt** [comment]
It may have already been solved, if it doesn't happen in the src folder. Thomas is AFK for a few days, but said he'd hand over publishing rights so I can test that next week. Hold tight!

**Comment by Berkmann18** [comment]
Okay :).
