### ISSUE TITLE
bug: Map is undefined

### ISSUE THREAD

**Issue by RichardLitt** [tgetgood/whodunnit#3]
```sh
> name-your-contributors -u mntnr -r name-your-contributors | src/cli.js
TypeError: Cannot read property 'map' of undefined
    at cat (/Users/richard/src/whodunnit/src/index.js:20:19)
    at loopField (/Users/richard/src/whodunnit/src/index.js:23:30)
    at typeMap.map (/Users/richard/src/whodunnit/src/index.js:46:27)
    at Array.map (native)
    at byUser (/Users/richard/src/whodunnit/src/index.js:46:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)
```

**Comment by tgetgood** [comment]
I can't replicate this with either branch of name-your-contributors. Are you using master of both nyc and whodunnit? 

It's conceivably (but very unlikely) a node version issue since some es6 features weren't in until 6.12.0. I've bumped the version just in case, but I'm not counting on that being the problem.

**Comment by RichardLitt** [comment]
Probably an issue with an old name-your-contributors version, now that I'm looking at it. Let's merge https://github.com/mntnr/name-your-contributors/pull/43 and then come back to this?

**Comment by RichardLitt** [comment]
Not an issue anymore.
